# Site settings
title: Tsinghua Number Theory Group
description: Number Theory Team in Tsinghua University
baseurl: / # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title:output_ext
